### ISSUE TITLE
Error when using npm start

### ISSUE THREAD

**Issue by mding5692** [meanie/angular-seed#1]
I installed all the dependencies and then type npm start

This is what I get:

```
Error: Unbalanced delimiter found in string
    at Function.XRegExp.matchRecursive (/Users/mding/Desktop/pubnub-financial/node_modules/gulp-preprocess/node_modules/preprocess/node_modules/xregexp/src/addons/matchrecursive.js:176:23)
    at matchReplacePass (/Users/mding/Desktop/pubnub-financial/node_modules/gulp-preprocess/node_modules/preprocess/lib/preprocess.js:291:27)
```

**Comment by adamreisnz** [comment]
Thanks, I'll have a look. I've neglected the Angular 1 seed a bit lately, I might update it to use the new ui-router and component routing while I'm at it.

**Comment by adamreisnz** [comment]
@mding5692 I've upgraded the Angular seed and updated Angular to 1.6.1 and ui-router to 1.0.0.
The project now builds and runs successfully, please let me know if you still encounter issues with the latest version.
